### ISSUE TITLE
Unable To Upload Photos

### ISSUE THREAD

**Issue by ajheisler** [zhxie/projects-dance#1]
I can add a new item but unable to add photos. When I select the photos and choose to upload them, I get a "Bad Gateway" error.

**Comment by zhxie** [comment]
fixed with https://github.com/zhxie/edancemarket-prod/commit/bb38f64636b0ce46fe034a7ca775a8ea2248d04d

**Comment by ajheisler** [comment]
Still not able to filter dresses correctly. I tried searching for a pink dress. Got 0 results.
